number_of_lanes: 24
#
lane_1:
  road_id: 2
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 1
#
lane_2:
  road_id: 3
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 1
#
lane_3:
  road_id: 4
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 1
#
lane_4:
  road_id: 5
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 1
#
lane_5:
  road_id: 7
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 1
#
lane_6:
  road_id: 8
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 1
#
lane_7:
  road_id: 9
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 1
#
lane_8:
  road_id: 10
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 1
#
lane_9:
  road_id: 15
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 3
#
lane_10:
  road_id: 16
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 3
#
lane_11:
  road_id: 17
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 3
#
lane_12:
  road_id: 18
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 3
#
lane_13:
  road_id: 20
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 3
#
lane_14:
  road_id: 21
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 3
#
lane_15:
  road_id: 22
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 3
#
lane_16:
  road_id: 23
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 3
#
lane_17:
  road_id: 30
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 2
#
lane_18:
  road_id: 31
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 2
#
lane_19:
  road_id: 35
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 2
#
lane_20:
  road_id: 36
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 2
#
lane_21:
  road_id: 58
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 4
#
lane_22:
  road_id: 59
  lane_id: 1
  intersection_id: 2
  traffic_light_id: 4
#
lane_23:
  road_id: 63
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 4
#
lane_24:
  road_id: 64
  lane_id: 1
  intersection_id: 1
  traffic_light_id: 4
