number_of_lanes: 77
#
lane_1:
  road_id: 3
  lane_id: 1
  intersection_id: 10170
  traffic_light_id: 3
#
lane_2:
  road_id: 4
  lane_id: 1
  intersection_id: 10170
  traffic_light_id: 3
#
lane_3:
  road_id: 7
  lane_id: 1
  intersection_id: 10180
  traffic_light_id: 2
#
lane_4:
  road_id: 8
  lane_id: 1
  intersection_id: 10180
  traffic_light_id: 2
#
lane_5:
  road_id: 13
  lane_id: 1
  intersection_id: 10190
  traffic_light_id: 3
#
lane_6:
  road_id: 14
  lane_id: 1
  intersection_id: 10190
  traffic_light_id: 3
#
lane_7:
  road_id: 17
  lane_id: 1
  intersection_id: 10200
  traffic_light_id: 2
#
lane_8:
  road_id: 18
  lane_id: 1
  intersection_id: 10200
  traffic_light_id: 2
#
lane_9:
  road_id: 21
  lane_id: 1
  intersection_id: 10210
  traffic_light_id: 2
#
lane_10:
  road_id: 22
  lane_id: 1
  intersection_id: 10210
  traffic_light_id: 2
#
lane_11:
  road_id: 25
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 3
#
lane_12:
  road_id: 26
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 3
#
lane_13:
  road_id: 27
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 3
#
lane_14:
  road_id: 35
  lane_id: 1
  intersection_id: 10010
  traffic_light_id: 3
#
lane_15:
  road_id: 36
  lane_id: 1
  intersection_id: 10010
  traffic_light_id: 3
#
lane_16:
  road_id: 39
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 2
#
lane_17:
  road_id: 40
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 2
#
lane_18:
  road_id: 41
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 2
#
lane_19:
  road_id: 44
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 2
#
lane_20:
  road_id: 45
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 2
#
lane_21:
  road_id: 46
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 2
#
lane_22:
  road_id: 49
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 2
#
lane_23:
  road_id: 50
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 2
#
lane_24:
  road_id: 51
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 2
#
lane_25:
  road_id: 56
  lane_id: 1
  intersection_id: 10050
  traffic_light_id: 1
#
lane_26:
  road_id: 57
  lane_id: 1
  intersection_id: 10050
  traffic_light_id: 1
#
lane_27:
  road_id: 63
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 1
#
lane_28:
  road_id: 64
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 1
#
lane_29:
  road_id: 65
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 1
#
lane_30:
  road_id: 68
  lane_id: 1
  intersection_id: 10140
  traffic_light_id: 1
#
lane_31:
  road_id: 69
  lane_id: 1
  intersection_id: 10140
  traffic_light_id: 1
#
lane_32:
  road_id: 72
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 2
#
lane_33:
  road_id: 73
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 2
#
lane_34:
  road_id: 76
  lane_id: 1
  intersection_id: 10050
  traffic_light_id: 2
#
lane_35:
  road_id: 77
  lane_id: 1
  intersection_id: 10050
  traffic_light_id: 2
#
lane_36:
  road_id: 82
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 3
#
lane_37:
  road_id: 83
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 3
#
lane_38:
  road_id: 84
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 3
#
lane_39:
  road_id: 87
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 3
#
lane_40:
  road_id: 88
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 3
#
lane_41:
  road_id: 89
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 3
#
lane_42:
  road_id: 92
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 4
#
lane_43:
  road_id: 93
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 4
#
lane_44:
  road_id: 94
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 4
#
lane_45:
  road_id: 105
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 1
#
lane_46:
  road_id: 106
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 1
#
lane_47:
  road_id: 107
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 1
#
lane_48:
  road_id: 110
  lane_id: 1
  intersection_id: 10210
  traffic_light_id: 1
#
lane_49:
  road_id: 111
  lane_id: 1
  intersection_id: 10210
  traffic_light_id: 1
#
lane_50:
  road_id: 114
  lane_id: 1
  intersection_id: 10200
  traffic_light_id: 1
#
lane_51:
  road_id: 115
  lane_id: 1
  intersection_id: 10200
  traffic_light_id: 1
#
lane_52:
  road_id: 118
  lane_id: 1
  intersection_id: 10190
  traffic_light_id: 1
#
lane_53:
  road_id: 119
  lane_id: 1
  intersection_id: 10190
  traffic_light_id: 1
#
lane_54:
  road_id: 122
  lane_id: 1
  intersection_id: 10180
  traffic_light_id: 1
#
lane_55:
  road_id: 123
  lane_id: 1
  intersection_id: 10180
  traffic_light_id: 1
#
lane_56:
  road_id: 126
  lane_id: 1
  intersection_id: 10170
  traffic_light_id: 1
#
lane_57:
  road_id: 127
  lane_id: 1
  intersection_id: 10170
  traffic_light_id: 1
#
lane_58:
  road_id: 130
  lane_id: 1
  intersection_id: 10140
  traffic_light_id: 2
#
lane_59:
  road_id: 131
  lane_id: 1
  intersection_id: 10140
  traffic_light_id: 2
#
lane_60:
  road_id: 136
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 4
#
lane_61:
  road_id: 137
  lane_id: 1
  intersection_id: 10220
  traffic_light_id: 4
#
lane_62:
  road_id: 142
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 3
#
lane_63:
  road_id: 143
  lane_id: 1
  intersection_id: 10020
  traffic_light_id: 3
#
lane_64:
  road_id: 151
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 1
#
lane_65:
  road_id: 152
  lane_id: 1
  intersection_id: 10040
  traffic_light_id: 1
#
lane_66:
  road_id: 154
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 1
#
lane_67:
  road_id: 155
  lane_id: 1
  intersection_id: 10030
  traffic_light_id: 1
#
lane_68:
  road_id: 102
  lane_id: 1
  intersection_id: 20010
  traffic_light_id: 1
#
lane_69:
  road_id: 30
  lane_id: 1
  intersection_id: 20010
  traffic_light_id: 2
#
lane_70:
  road_id: 148
  lane_id: 1
  intersection_id: 20010
  traffic_light_id: 3
#
lane_71:
  road_id: 149
  lane_id: 1
  intersection_id: 20010
  traffic_light_id: 3
#
lane_72:
  road_id: 145
  lane_id: 1
  intersection_id: 20020
  traffic_light_id: 1
#
lane_73:
  road_id: 139
  lane_id: 1
  intersection_id: 20020
  traffic_light_id: 2
#
lane_74:
  road_id: 140
  lane_id: 1
  intersection_id: 20020
  traffic_light_id: 2
#
lane_75:
  road_id: 134
  lane_id: 1
  intersection_id: 20020
  traffic_light_id: 3
#
lane_76:
  road_id: 159
  lane_id: 1
  intersection_id: 10160
  traffic_light_id: 2
#
lane_77:
  road_id: 157
  lane_id: 1
  intersection_id: 10170
  traffic_light_id: 1
