number_of_lanes: 20
#
lane_1:
  road_id: 2
  lane_id: 1
  intersection_id: 000
  traffic_light_id: 1
#
lane_2:
  road_id: 14
  lane_id: 1
  intersection_id: 000
  traffic_light_id: 1
#
lane_3:
  road_id: 25
  lane_id: 1
  intersection_id: 000
  traffic_light_id: 1
#
lane_4:
  road_id: 6
  lane_id: 1
  intersection_id: 100
  traffic_light_id: 1
#
lane_5:
  road_id: 9
  lane_id: 1
  intersection_id: 100
  traffic_light_id: 1
#
lane_6:
  road_id: 18
  lane_id: 1
  intersection_id: 100
  traffic_light_id: 1
#
lane_7:
  road_id: 16
  lane_id: 1
  intersection_id: 200
  traffic_light_id: 1
#
lane_8:
  road_id: 11
  lane_id: 1
  intersection_id: 200
  traffic_light_id: 1
#
lane_9:
  road_id: 19
  lane_id: 1
  intersection_id: 200
  traffic_light_id: 1
#
lane_10:
  road_id: 20
  lane_id: 1
  intersection_id: 200
  traffic_light_id: 1
#
lane_11:
  road_id: 29
  lane_id: 1
  intersection_id: 200
  traffic_light_id: 1
#
lane_12:
  road_id: 22
  lane_id: 1
  intersection_id: 001
  traffic_light_id: 1
#
lane_13:
  road_id: 27
  lane_id: 1
  intersection_id: 001
  traffic_light_id: 1
#
lane_14:
  road_id: 30
  lane_id: 1
  intersection_id: 001
  traffic_light_id: 1
#
lane_15:
  road_id: 8
  lane_id: 1
  intersection_id: 300
  traffic_light_id: 1
#
lane_16:
  road_id: 13
  lane_id: 1
  intersection_id: 300
  traffic_light_id: 1
#
lane_17:
  road_id: 24
  lane_id: 1
  intersection_id: 300
  traffic_light_id: 1
#
lane_18:
  road_id: 38
  lane_id: 1
  intersection_id: 400
  traffic_light_id: 1
#
lane_19:
  road_id: 40
  lane_id: 1
  intersection_id: 500
  traffic_light_id: 1
#
lane_20:
  road_id: 42
  lane_id: 1
  intersection_id: 700
  traffic_light_id: 1

